package business;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.event.ActionEvent;

public class GUIWelcomeController {
	@FXML
	private Button bPlay;

	// Event Listener on Button[#bPlay].onAction
	@FXML
	public void bPlayAction(ActionEvent event) {
		// TODO Autogenerated
	}
}
